### PR TITLE
New tutorial: Using NAMD with Flight Compute

### PR DESCRIPTION
**Pull request by vlj91**
- Refs #29 

There's quite a lot of steps to get going (building protein structures to use etc) to the 'using NAMD' bit, so I've done those and packaged them up. This cuts the tutorial down to actually just using NAMD. 

If you would rather the prerequisite steps were included, I can modify it to include those steps.

The tutorial is roughly based on: http://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix.pdf

### CODE REVIEW

**Comment by vlj91** [comment]
@wdm78 if you could check this when possible please - if you can't build a copy locally I can create a protected build on RTD

**Comment by wdm78** [comment]
@vlj91 - Yes please; if you can build it on RTD and point me at it please, then I'll take a look thru. Thanks!

**Comment by vlj91** [comment]
Private build: http://docs.alces-flight.com/en/tutorials-namd/getting-started/environment-usage/using-namd-with-alces-flight-compute.html

**Comment by wdm78** [comment]
This tutorial has been rewritten and added to 2016.4 docs - this PR can be closed

**Pull request closed without merging**
